trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'
  
container: Ubuntu:16.04

variables:
  dockerId: dlh0092  # Replace with your Docker ID for Docker Hub or the admin user name for the Azure Container Registry
  imageName: pipelines-dotnet-core-docker  # Replace with the name of the image you want to publish

steps:
- script: |
    docker build -t dlh0092.azurecr.io/$(imageName) .
    docker login -u $(dockerId) -p $(pswd) dlh0092.azurecr.io
    docker push dlh0092.azurecr.io/$(imageName)
  env:
    pswd: $(dockerPassword)        # Define dockerPassword in the Variables tab of this pipeline in Pipelines page of web interface